Repository prgrms-be-devcourse/NBE-4-5-1-Team02, pull requests merged in 2025-02, with the labels that each got.

#7 product entity, order entity 작성
  src/main/java/com/team2/demo/order/Order.java
  src/main/java/com/team2/demo/product/Product.java
Labels: feature

#18 [feat] : 주문 리스트 조회 ( 사용자 )
  db.trace.db
  src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  src/main/java/com/team2/demo/domain/order/dto/OrderDto.java
  src/main/java/com/team2/demo/domain/order/entity/Order.java
  src/main/java/com/team2/demo/domain/order/repository/OrderRepository.java
  src/main/java/com/team2/demo/domain/order/service/OrderService.java
  src/main/java/com/team2/demo/domain/product/controller/ProductController.java
  src/main/java/com/team2/demo/domain/user/entity/User.java
  src/main/java/com/team2/demo/global/response/OrderListResponse.java
  src/main/java/com/team2/demo/global/response/RsData.java
Labels: feature

#16 [feat] : 상품 목록 조회 ( 사용자 )
  .gitignore
  Docs/API.md
  src/main/java/com/team2/demo/domain/order/entity/Order.java
  src/main/java/com/team2/demo/domain/product/controller/ProductController.java
  src/main/java/com/team2/demo/domain/product/dto/ProductDto.java
  src/main/java/com/team2/demo/domain/product/repository/ProductRepository.java
  src/main/java/com/team2/demo/domain/product/service/ProductService.java
  src/main/java/com/team2/demo/domain/user/entity/User.java
  src/main/java/com/team2/demo/global/response/PaginationData.java
  src/main/java/com/team2/demo/global/response/RsData.java
  src/main/resources/application.yml
Labels: feature

#27 [feat] : DB 초기 데이터 추가
  .gitignore
  db.trace.db
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: feature

#25 [feat] : 유저 생성 (사용자)
  .gitignore
  src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  src/main/java/com/team2/demo/domain/order/dto/OrderDto.java
  src/main/java/com/team2/demo/domain/order/entity/Order.java
  src/main/java/com/team2/demo/domain/order/repository/OrderRepository.java
  src/main/java/com/team2/demo/domain/order/service/OrderService.java
  src/main/java/com/team2/demo/domain/user/controller/UserController.java
  src/main/java/com/team2/demo/domain/user/dto/UserDto.java
  src/main/java/com/team2/demo/domain/user/entity/User.java
  src/main/java/com/team2/demo/domain/user/repository/UserRepository.java
  src/main/java/com/team2/demo/domain/user/service/UserService.java
Labels: feature

#24 [feat] : 리스트 조회(관리자)
  src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  src/main/java/com/team2/demo/domain/order/controller/OrderControllerAdmin.java
  src/main/java/com/team2/demo/domain/order/dto/OrderDto.java
  src/main/java/com/team2/demo/domain/order/service/OrderService.java
  src/main/java/com/team2/demo/domain/product/controller/ProductController.java
  src/main/java/com/team2/demo/global/response/RsData.java
Labels: feature

#26 [feat] : 주문 수정 (사용자)
  src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  src/main/java/com/team2/demo/domain/order/dto/OrderDto.java
  src/main/java/com/team2/demo/domain/order/dto/OrderRequestDto.java
  src/main/java/com/team2/demo/domain/order/entity/Order.java
  src/main/java/com/team2/demo/domain/order/repository/OrderRepository.java
  src/main/java/com/team2/demo/domain/order/service/OrderService.java
  src/main/java/com/team2/demo/domain/product/repository/ProductRepository.java
  src/main/java/com/team2/demo/global/response/RsData.java
Labels: feature

#30 [fix]: 에러 수정
  src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  src/main/java/com/team2/demo/domain/order/service/OrderService.java
  src/main/java/com/team2/demo/domain/user/controller/UserController.java
  src/main/java/com/team2/demo/global/response/RsData.java
Labels: bug

#35 [fix] : 에러 수정
  db.trace.db
  src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  src/main/java/com/team2/demo/domain/order/dto/OrderDto.java
  src/main/java/com/team2/demo/domain/order/entity/Order.java
  src/main/java/com/team2/demo/domain/order/service/OrderService.java
Labels: bug

#38 [feat] : 주문 상세 조회 (관리자)
  Docs/API.md
  src/main/java/com/team2/demo/domain/order/controller/OrderControllerAdmin.java
  src/main/java/com/team2/demo/domain/order/dto/OrderInfoDtoAdmin.java
  src/main/java/com/team2/demo/domain/order/dto/OrderInfoWithoutItemDto.java
  src/main/java/com/team2/demo/domain/order/repository/OrderRepository.java
  src/main/java/com/team2/demo/domain/order/service/OrderService.java
  src/main/java/com/team2/demo/domain/product/controller/ProductController.java
  src/main/java/com/team2/demo/domain/product/repository/ProductRepository.java
  src/main/java/com/team2/demo/domain/product/service/ProductService.java
  src/test/java/com/team2/demo/domain/product/repository/ProductRepositoryTest.java
Labels: feature

#44 [feat] : 주문 리스트 조회 (관리자) 기능 수정
  src/main/java/com/team2/demo/domain/order/controller/OrderControllerAdmin.java
  src/main/java/com/team2/demo/domain/order/dto/OrderDto.java
  src/main/java/com/team2/demo/domain/order/dto/OrderItemGrouper.java
  src/main/java/com/team2/demo/domain/order/service/OrderService.java
Labels: feature

#39 [feat] : 주문 수정(관리자)
  gradlew
  gradlew.bat
  src/main/java/com/team2/demo/domain/order/controller/OrderControllerAdmin.java
  src/main/java/com/team2/demo/domain/order/entity/Order.java
  src/main/java/com/team2/demo/domain/order/service/AdminOrderService.java
  src/main/java/com/team2/demo/domain/order/service/OrderService.java
Labels: feature

#46 [feat] : 주문 생성 (사용자)
  .gitignore
  Docs/API.md
  db.trace.db
  src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  src/main/java/com/team2/demo/domain/order/entity/Order.java
  src/main/java/com/team2/demo/domain/user/repository/UserRepository.java
  src/main/java/com/team2/demo/domain/user/service/UserService.java
  src/main/java/com/team2/demo/global/response/RsData.java
Labels: feature

#52 feat: 주문 취소 (사용자)
  .idea/.name
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/demo.main.iml
  .idea/sqldialects.xml
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  backend/src/main/java/com/team2/demo/domain/order/entity/Order.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
Labels: feature

#53 feat:관리자 주문 삭제
  .idea/misc.xml
  backend/gradlew
  backend/gradlew.bat
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderControllerAdmin.java
  backend/src/main/java/com/team2/demo/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/team2/demo/domain/order/service/AdminOrderService.java
Labels: feature

#61 [bug] : productController 수정
  README.md
  backend/src/main/java/com/team2/demo/domain/product/controller/ProductController.java
  backend/src/main/java/com/team2/demo/domain/product/service/ProductService.java
  backend/src/main/java/com/team2/demo/global/exception/GlobalExceptionAdvisor.java
  backend/src/main/java/com/team2/demo/global/exception/ServiceException.java
  backend/src/main/java/com/team2/demo/global/exception/prodcut/UnsupportedProductKeywordTypeException.java
  backend/src/main/java/com/team2/demo/global/response/RsData.java
  backend/src/test/java/com/team2/demo/domain/product/controller/ProductControllerTest.java
Labels: bug

#64 [test]: 주문 리스트 조회 (사용자, 관리자) 테스트 작성
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderControllerAdmin.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
  backend/src/main/java/com/team2/demo/global/exception/GlobalExceptionAdvisor.java
  backend/src/main/java/com/team2/demo/global/exception/ServiceException.java
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerAdminTest.java
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerTest.java
Labels: test

#67 [bug] : 사용자 주문 수정시 총 가격이 업데이트되지 않는 오류 수정
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  backend/src/main/java/com/team2/demo/domain/order/dto/OrderRequestDto.java
  backend/src/main/java/com/team2/demo/domain/order/dto/ProductWithAmount.java
  backend/src/main/java/com/team2/demo/domain/order/entity/Order.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
  backend/src/main/java/com/team2/demo/domain/product/dto/ProductListDto.java
  backend/src/main/java/com/team2/demo/domain/user/entity/User.java
  backend/src/main/java/com/team2/demo/global/exception/ServiceException.java
  backend/src/main/java/com/team2/demo/global/exception/order/NoProductsInOrderException.java
  backend/src/main/java/com/team2/demo/global/exception/user/AccessDeniedException.java
Labels: bug

#63 [test]: 관리자 주문 조회 상세 테스트 작성 및 예외 처리
  backend/src/main/java/com/team2/demo/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
  backend/src/main/java/com/team2/demo/domain/product/service/ProductService.java
  backend/src/main/java/com/team2/demo/global/exception/ServiceException.java
  backend/src/main/java/com/team2/demo/global/exception/order/NoSuchOrderException.java
  backend/src/main/java/com/team2/demo/global/exception/product/UnsupportedProductKeywordTypeException.java
  backend/src/test/java/com/team2/demo/CaffeApplicationTests.java
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerAdminTest.java
Labels: feature

#74 chrone: spring-boot-starter-validation 의존성 추가
  backend/build.gradle
Labels: chore

#65 [bug] : 사용자 주문 수정 시 productIds null 체크 추가 및 NPE 방지
  backend/Docs/API.md
  backend/src/main/java/com/team2/demo/domain/order/dto/OrderRequestDto.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
Labels: bug

#70 Revert "[test]: 주문 리스트 조회 (사용자, 관리자) 테스트 작성"
  backend/build.gradle
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderControllerAdmin.java
  backend/src/main/java/com/team2/demo/domain/order/dto/OrderDto.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
  backend/src/main/java/com/team2/demo/domain/product/service/ProductService.java
  backend/src/main/java/com/team2/demo/global/exception/GlobalExceptionAdvisor.java
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerAdminTest.java
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerTest.java
Labels: test

#78 [docs] : swagger ui 추가
  backend/build.gradle
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderControllerAdmin.java
  backend/src/main/java/com/team2/demo/domain/product/controller/ProductController.java
  backend/src/main/java/com/team2/demo/global/SpringDocConfig.java
Labels: docs

#82 [bug] : OrderControllerAdmin에서 Order 객체를 파라미터에 그대로 노출시키는 문제 해결
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderControllerAdmin.java
  backend/src/main/java/com/team2/demo/domain/order/service/AdminOrderService.java
  backend/src/main/java/com/team2/demo/domain/product/entity/Product.java
Labels: bug

#55 docs: api docs 문서 수정
  .idea/modules/NBE-4-5-1-Team2.iml
  .idea/workspace.xml
  backend/Docs/API.md
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  backend/src/main/java/com/team2/demo/domain/user/controller/UserController.java
  backend/src/main/java/com/team2/demo/domain/user/repository/UserRepository.java
  frontend/.idea/.gitignore
  frontend/.idea/frontend.iml
  frontend/.idea/inspectionProfiles/Project_Default.xml
  frontend/.idea/misc.xml
  frontend/.idea/vcs.xml
  frontend/package-lock.json
Labels: feature, docs

#80 [feat] : frontend 패키지 구조 설계
  frontend/src/app/admin/orders/[orderId]/page.tsx
  frontend/src/app/admin/orders/api.ts
  frontend/src/app/admin/orders/page.tsx
  frontend/src/app/orders/[orderId]/page.tsx
  frontend/src/app/orders/api.tsx
  frontend/src/app/orders/page.tsx
  frontend/src/app/products/api.ts
  frontend/src/app/products/page.tsx
  frontend/src/app/products/productId/page.tsx
  frontend/src/components/OrderItem.tsx
  frontend/src/components/Pagination.tsx
  frontend/src/components/ProductCard.tsx
  frontend/src/docs/_document.tsx
  frontend/src/docs/폴더_설계.md
  frontend/src/hooks/useOrders.ts
  frontend/src/hooks/useProducts.ts
  frontend/src/services/api.ts
  frontend/src/styles/globals.css
  frontend/src/styles/theme.ts
  frontend/src/utils/utility.ts
Labels: feature

#88 [bug] : 스토리 보드와 API 설계의 속성 차이 문제
  backend/Docs/API.md
  backend/src/main/java/com/team2/demo/domain/order/dto/OrderDto.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerTest.java
Labels: feature

#96 [bug] : 사용자 주문 생성시 order에 product가 들어가지 않는 오류
  backend/.gitignore
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  backend/src/main/java/com/team2/demo/domain/order/dto/OrderRequestDto.java
  backend/src/main/java/com/team2/demo/domain/order/entity/Order.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
  backend/src/main/java/com/team2/demo/domain/user/dto/UserDto.java
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerTest.java
Labels: bug

#92 [bug] : BE - 주문 취소 (사용자) 응답 수정
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  backend/src/main/java/com/team2/demo/domain/order/dto/OrderResponseCancelDto.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerTest.java
Labels: bug

#100 [feat] : FE - 메인 페이지 작성
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/team2/demo/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
  backend/src/main/java/com/team2/demo/domain/product/controller/ProductController.java
  backend/src/main/java/com/team2/demo/global/filter/CorsFilter.java
  backend/src/main/java/com/team2/demo/util/DevInitData.java
  backend/src/main/resources/data.sql
  frontend/components.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/image.png
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/ClientPage.tsx
  frontend/src/app/globals.css
  frontend/src/app/home/ProductList/ProductList.tsx
  frontend/src/app/home/ProductList/SearchInput.tsx
  frontend/src/app/home/ProductSummary/ProductSummary.tsx
  frontend/src/app/home/UserDataInput.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/pagination.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/lib/utils.ts
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: feature

#106 [test] 주문삭제(관리자)
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerAdminTest.java
Labels: test

#101 [test] 주문수정(관리자)
  backend/src/main/java/com/team2/demo/domain/order/dto/OrderRequestDto.java
  backend/src/main/java/com/team2/demo/domain/order/service/AdminOrderService.java
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerAdminTest.java
Labels: test

#111 [feat] : [feat] : FE - 구현된 페이지 UI 꾸미기
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/ClientPage.tsx
  frontend/src/app/admin/orders/AdminOrdersClientPage.tsx
  frontend/src/app/globals.css
  frontend/src/app/home/ProductList/ProductList.tsx
  frontend/src/app/home/ProductList/SearchInput.tsx
  frontend/src/app/home/ProductSummary/ProductSummary.tsx
  frontend/src/app/home/UserDataInput.tsx
  frontend/src/app/orders/EmailModal.tsx
  frontend/src/app/orders/OrderClientPage.tsx
  frontend/src/app/orders/api.ts
  frontend/src/components/OrderConfirmModal.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/command.tsx
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/scroll-area.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/components/ui/tooltip.tsx
Labels: feature

#112 feat: FE - 관리자 고객 조회 수정 페이지 기본 요구사항 기능 구현
  backend/.gitignore
  backend/apiV1.json
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderControllerAdmin.java
  backend/src/main/java/com/team2/demo/domain/order/dto/OrderRequestDto.java
  backend/src/main/java/com/team2/demo/domain/order/entity/Order.java
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
  backend/src/test/java/com/team2/demo/domain/order/controller/OrderControllerTest.java
  frontend/src/app/admin/orders/[orderId]/update/page.tsx
Labels: feature

#118 [bug] : FE - 사용자 주문 상세에서 주문 수정 버튼으로 안넘어감
  frontend/src/app/orders/[orderId]/ClientPage.tsx
Labels: bug

#120 [feat] : BE - 배송 배치 프로세스 작성
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/team2/demo/domain/order/entity/Order.java
  backend/src/main/java/com/team2/demo/global/batch/BatchController.java
  backend/src/main/java/com/team2/demo/global/batch/DeliveryOrderJobConfig.java
  backend/src/main/java/com/team2/demo/global/batch/H2DeliveryOrderJobConfig.java
  backend/src/main/java/com/team2/demo/global/batch/JobExecutor.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/data2.sql
  backend/src/main/resources/schema.sql
Labels: feature

#121 [bug] : FE - 사용자 주문 수정 오류
  backend/src/main/java/com/team2/demo/domain/order/entity/Order.java
  frontend/src/components/OrderUpdate/OrderDetails.tsx
  frontend/src/hooks/useOrders.ts
  frontend/src/services/orderService.ts
Labels: bug

#125 refactor. 관리자 고객 조회 수정 페이지 추가 기능 구현
  backend/Docs/API.md
  backend/apiV1.json
  backend/src/main/java/com/team2/demo/domain/order/controller/OrderController.java
  frontend/src/app/admin/orders/AdminOrdersClientPage.tsx
  frontend/src/app/admin/orders/[orderId]/AdminOrderDetailClientPage.tsx
Labels: feature, refactor

#131 [docs] : api 문서 수정
  backend/Docs/API.md
  backend/src/main/java/com/team2/demo/domain/order/service/OrderService.java
  frontend/src/app/orders/[orderId]/ClientPage.tsx
Labels: feature

#135 [bug] : 관리자 주문 수정에서 상품을 업데이트 했을 때 반영되지 않는 오류
  backend/.gitignore
  backend/src/main/java/com/team2/demo/domain/order/service/AdminOrderService.java
Labels: bug

#137 [feat] : FE - 사용자 주문 수정 페이지 ui 수정
  frontend/src/app/orders/[orderId]/update/page.tsx
  frontend/src/components/OrderUpdate/AvailableProducts.tsx
  frontend/src/components/OrderUpdate/OrderDetails.tsx
  frontend/src/components/OrderUpdate/OrderProductList.tsx
  frontend/src/hooks/useOrders.ts
Labels: feature

#138 refactor. FE - 주문 상세 정보 수정 페이지 ( 관리자 )
  frontend/src/app/admin/orders/[orderId]/AdminOrderDetailClientPage.tsx
Labels: refactor
